server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ciphersqlstudio_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent-output: true

llm:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
management:
  endpoints:
    web:
      exposure:
        include: mappings

